### ISSUE TITLE
Node size not comply with alteration data

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/pathway-mapper#257]
After a node is removed from its parent, its size doesn't change according to the alteration data it shows. 

https://user-images.githubusercontent.com/22586369/122918375-bc596700-d367-11eb-89c9-282649cf54ab.mp4

**Comment by hasanbalci** [comment]
It seems fixed in local mode. But I realized that node sizes are not adjusted on alteration data changes in collaborative mode. 
![image](https://user-images.githubusercontent.com/22586369/123066495-cab38b80-d418-11eb-99e3-c680519ee01e.png)

**Comment by ugurdogrusoz** [comment]
@msalihaltun I think the collaborative mode still doesn't work in the same way as the local one (no resize on loading more than 3 data sets)

**Comment by msalihaltun** [comment]
Let's test again now. I keep running into "one off" problems with alteration data and width that I can't reproduce.

**Comment by msalihaltun** [comment]
There are also some issues in collaborative where node style won't update, selection etc. will update it and change node width. Can't reliably reproduce though.

**Comment by ugurdogrusoz** [comment]
From what I can tell, auto-resizing of nodes upon data load / enable seems to be working in both modes now. @hasanbalci please test.

**Comment by hasanbalci** [comment]
Auto-resizing of nodes upon data load / enable works initially (node sizes becomes larger) but when I select a node, it becomes smaller again and doesn't fit to data.

**Comment by hasanbalci** [comment]
It seems ok now, thanks!
